src/ISCAP/Models/SlotBlock.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ISCAP.Models
{
    public class SlotBlock
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int slotBlockId { get; set; }
        [Required]
        public string title { get; set; }
        [ForeignKey("slotId")]
        [Display(Name ="Slots")]
        public int slotId { get; set; }
    }
}

src/ISCAP/Controllers/SlotBlockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ISCAP.Data;
using ISCAP.Models;

namespace ISCAP.Controllers
{
    public class SlotBlockController : Controller
    {
        public readonly ApplicationDbContext _context;
        
        public SlotBlockController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(Slot Slot)
        {
            if(Slot.slotId == 0)
            {
                ModelState.AddModelError("", "Select Slot");
            }

            int SelectValue = Slot.slotId;

            ViewBag.SelectedValue = Slot.slotId;

            List<Slot> slotList = new List<Slot>();

            slotList = (from block in _context.Slot select block).ToList();

            slotList.Insert(0, new Slot { slotId = 0, title = "Select" });

            ViewBag.ListOfSlots = slotList;
            return View();
        }

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveSlotBlock([Bind("slotBlockId,title")] SlotBlock slotBlock)
        {
            if (ModelState.IsValid)
            {

                _context.Add(slotBlock);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(slotBlock);
        }*/
    }
}

src/ISCAP/Views/SlotBlock/Index.cshtml
@model ISCAP.Models.SlotBlock

@{
        <form asp-controller="SlotBlock" asp-action="Index" method="post" class="form-horizontal" role="form">
            <div class="form-group">
                <div class="role">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        <label asp-for="title" class="control-label-label"></label>
                        <select asp-for="slotId"
                                class="form-control"
                                asp-items="@(new SelectList(ViewBag.ListOfSlots,"slotId", "title"))"></select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        <input id="Submit" type="submit" value="submit" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        @if (ViewBag.SelectedValue != null)
                        {
                            <text>Selected Slock Block ID: </text> @ViewBag.SelectedValue;
                        }
                    </div>
                </div>
            </div>  
        </form>
}