src/ISCAP/Controllers/SlotContainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ISCAP.Models;
using ISCAP.Data;
using static ISCAP.Models.GetConString;

namespace ISCAP.Controllers
{
    public class SlotContainerController : Controller
    {
        public ApplicationDbContext _context { get; set; }

        public SlotContainerController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        /*public IActionResult PanelDropDown(Panel Panel)
        {
            if (Panel.panelId == 0)
            {
                ModelState.AddModelError("", "Select Panel");
            }

            int SelectValue = Panel.panelId;

            ViewBag.SelectedValue = Panel.panelId;

            List<Panel> panelList = new List<Panel>();

            panelList = (from block in _context.Panel select block).ToList();

            panelList.Insert(0, new Panel { panelId = 0, panelTitle = "Select" });

            ViewBag.ListOfPanels = panelList;
            return View();
        }

        public IActionResult WorkShopDropDown(Workshop Workshop)
        {
            if (Workshop.workShopId == 0)
            {
                ModelState.AddModelError("", "Select Workshop");
            }

            int SelectValue = Workshop.workShopId;

            ViewBag.SelectedValue = Workshop.workShopId;

            List<Workshop> workShopList = new List<Workshop>();

            workShopList = (from block in _context.WorkShop select block).ToList();

            workShopList.Insert(0, new Workshop { workShopId = 0, workShoptitle = "Select" });

            ViewBag.ListOfWorkShops = workShopList;
            return View();
        }

        public IActionResult EventDropDown(Event Event)
        {
            if (Event.eventID == 0)
            {
                ModelState.AddModelError("", "Select Event");
            }

            int SelectValue = Event.eventID;

            ViewBag.SelectedValue = Event.eventID;

            List<Event> eventList = new List<Event>();

            eventList = (from block in _context.Event select block).ToList();

            eventList.Insert(0, new Event { eventID = 0, EventName = "Select" });

            ViewBag.ListOfEvents = eventList;
            return View();
        }

        public IActionResult AbstractDropDown(Abstract Abstract)
        {
            if (Abstract.AbstractID == 0)
            {
                ModelState.AddModelError("", "Select Abstract");
            }

            int SelectValue = Abstract.AbstractID;

            ViewBag.SelectedValue = Abstract.AbstractID;

            List<Abstract> abstractList = new List<Abstract>();

            abstractList = (from block in _context.Abstract select block).ToList();

            abstractList.Insert(0, new Abstract { AbstractID = 0, Title = "Select" });

            ViewBag.ListOfEvents = abstractList;
            return View();
        }*/

        public IActionResult Slot()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetDetails()
        {
            Slot slot = new Slot();
            slot.title = HttpContext.Request.Form["txtTitle"].ToString();
            slot.conference = HttpContext.Request.Form["txtConference"].ToString();
            slot.authors = HttpContext.Request.Form["txtAuthors"].ToString();
            slot.slotTime = Convert.ToInt32(HttpContext.Request.Form["txtSlot Time"]);

            int result = slot.SaveDetails();
            if (result > 0)
            {
                ViewBag.Result = "Data Saved Successfully";
            }
            else
            {
                ViewBag.Result = "Something Went Wrong";
            }
            return View("Index");
        }
    }
}

src/ISCAP/Views/SlotContainer/Index.cshtml
@model ISCAP.Models.Slot

@{
    ViewBag.Title = "Slots";
}

<h1>Slots</h1>
<form asp-controller="SlotContainer" asp-action="GetDetails" method="post">
    <table>
        <tr>
            <td>Title :</td>
            <td><input name="txtTitle" type="text" /></td>
        </tr>
        <tr>
            <td>Conference :</td>
            <td><input name="txtConference" type="text" /></td>
        </tr>
        <tr>
            <td>Author :</td>
            <td><input name="txtAuthors" type="text" /></td>
        </tr>
        <tr>
            <td>Slot Time :</td>
            <td><input name="txtSlot Time" type="text" /></td>
        </tr>
        <tr>
            <td colspan="2"><input id="Submit1" type="submit" value="submit" /></td>
        </tr>
    </table>
</form>
<br /><br />

<h2 style="font-style:italic; color:deeppink">@ViewBag.Result</h2>

@{
    /*<form asp-controller="SlotContainer" asp-action="Index" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <div class="role">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <label asp-for="panelId" class="control-label-label"></label>
                    <select asp-for="panelId"
                            class="form-control"
                            asp-items="@(new SelectList(ViewBag.ListOfPanels,"panelId", "panelTitle"))"></select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <input id="Submit" type="submit" value="submit" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    @if (ViewBag.SelectedValue != null)
                    {
                        <text>Selected Slot ID: </text> @ViewBag.SelectedValue;
                    }
                </div>
            </div>
        </div>
    </form>*/
}

@{
    /*<form asp-controller="SlotContainer" asp-action="Index" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <div class="role">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <label asp-for="workShopId" class="control-label-label"></label>
                    <select asp-for="workShopId"
                            class="form-control"
                            asp-items="@(new SelectList(ViewBag.ListOfWorkShops,"workShopId", "workShopTitle"))"></select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <input id="Submit" type="submit" value="submit" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    @if (ViewBag.SelectedValue != null)
                    {
                        <text>Selected Slot ID: </text> @ViewBag.SelectedValue;
                    }
                </div>
            </div>
        </div>
    </form>*/
}

@{
    /*<form asp-controller="SlotContainer" asp-action="Index" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <div class="role">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <label asp-for="eventID" class="control-label-label"></label>
                    <select asp-for="eventID"
                            class="form-control"
                            asp-items="@(new SelectList(ViewBag.ListOfEvents,"eventID", "EventName"))"></select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <input id="Submit" type="submit" value="submit" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    @if (ViewBag.SelectedValue != null)
                    {
                        <text>Selected Slot ID: </text> @ViewBag.SelectedValue;
                    }
                </div>
            </div>
        </div>
    </form>*/
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}